// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASAfOI__lFfvRZEPTdRKhTjnbGkWft86k',
    appId: '1:34493968920:web:04bbca5c9a396e1bf6496d',
    messagingSenderId: '34493968920',
    projectId: 'sleeprivation',
    authDomain: 'sleeprivation.firebaseapp.com',
    storageBucket: 'sleeprivation.appspot.com',
    measurementId: 'G-3FWVX6ZB96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZzIPYJwoTktNAM7xKYEi3tEIbcTPGPVw',
    appId: '1:34493968920:android:98c02ef230e27ff9f6496d',
    messagingSenderId: '34493968920',
    projectId: 'sleeprivation',
    storageBucket: 'sleeprivation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0olUTZcJbSeS7-7g5ru8Gvo-R-QPymI',
    appId: '1:34493968920:ios:71c3d3902124dcf1f6496d',
    messagingSenderId: '34493968920',
    projectId: 'sleeprivation',
    storageBucket: 'sleeprivation.appspot.com',
    iosClientId: '34493968920-bti2r53h2j2cpoee6vb196g0nnbv5jqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0olUTZcJbSeS7-7g5ru8Gvo-R-QPymI',
    appId: '1:34493968920:ios:71c3d3902124dcf1f6496d',
    messagingSenderId: '34493968920',
    projectId: 'sleeprivation',
    storageBucket: 'sleeprivation.appspot.com',
    iosClientId: '34493968920-bti2r53h2j2cpoee6vb196g0nnbv5jqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );
}
